### ISSUE TITLE
温州新闻异常

### ISSUE THREAD

**Issue by ihuaer** [c1pher-cn/iptv-hangzhou-dianxin#1]
#EXTINF:-1 ,温州新闻
233.50.201.87:5140  
实际是CCTV1

经测试，地方台可以播放，但是是普屏，已舍弃。
建议再建一个播放文件，只保留16比9的高清频道

**Comment by c1pher-cn** [comment]
感谢反馈，地方台是别人提交的，我没挨个试。
我空了再继续整理下，我本意这里保留的都是高清频道
