### ISSUE TITLE
宁波可用 好像内网ip 即iptv口好像有心跳认证 长时间不访问频道会断开 

### ISSUE THREAD

**Issue by ssassassaassa** [c1pher-cn/iptv-hangzhou-dianxin#13]

**Comment by c1pher-cn** [comment]
需要在hotplug创建一个脚本让udpxy跟着重新启动即可以解决。
输入以下命令创建脚本
vi /etc/hotplug.d/iface/99-iptv.sh
贴入脚本内容
#!/bin/sh
[ "$ACTION" = ifup ] && [ "$INTERFACE" = IPTV ] &&
/etc/init.d/udpxy restart
保存退出后为脚本文件添加可执行权限：
chmod +x /etc/hotplug.d/iface/99-iptv.sh

**Comment by ssassassaassa** [comment]
我试了一下是爱快的问题，换了红米ax6000的相关openwrt固件不会断开了
