### ISSUE TITLE
作者不再更新维护了吗？

### ISSUE THREAD

**Issue by Ahuangshang** [c1pher-cn/iptv-hangzhou-dianxin#15]
上次不能用了以后服务报500，过了一阵子能用了，但是原有的一些频道清晰度下降了好多，求有IPTV的大佬抓包重新分享个吧

**Comment by c1pher-cn** [comment]
请给出具体清晰度下降的频道，谢谢

**Comment by Ahuangshang** [comment]
CCTV4，cctv11,cctv15,cctv17,

**Comment by Ahuangshang** [comment]
宁波1、宁波3、宁波4不能播放、宁波5是cctv1
