### ISSUE TITLE
问下各位的组播都正常么？

### ISSUE THREAD

**Issue by c1pher-cn** [c1pher-cn/iptv-hangzhou-dianxin#18]
我这边杭州电信，逻辑都没变突然上个月开始就获取不到私网ip了，重新抓包再配也不行

**Comment by Youwenqwq** [comment]
> Owner

温州电信，实测使用iKuai的DHCP上网方式，配置option12和option60即可正常获取到私网ip。VLAN单线复用和单独使用iPTV口都没有问题。

**Comment by c1pher-cn** [comment]
没事了，我自己的问题
