### ISSUE TITLE
稳定性怎么样？多久需要抓包一次？

### ISSUE THREAD

**Issue by 1021683053** [c1pher-cn/iptv-hangzhou-dianxin#5]
我有个想法，可不可以自动抓包，然后自动更新这个列表？

**Comment by c1pher-cn** [comment]
主要频道基本不会变，小的付费频道什么电视剧、电影频道、炫酷卡通、茶频道这种有时候会变
自己抓包当然可以，但是包里没有频道名，你需要人看或者自己做图像识别来映射。
如果有图像识别了不如自己做网段扫描来的快，我是这么觉得的
